# Generated by Django 3.2.4 on 2021-06-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=32, verbose_name='Hash Value')),
                ('region', models.CharField(max_length=256, verbose_name='Region')),
                ('origin_coord', models.CharField(max_length=46, verbose_name='Origin Coordenates')),
                ('destination_coord', models.CharField(max_length=46, verbose_name='Destination Coordenates')),
                ('date_time', models.DateTimeField(verbose_name='Date Time')),
                ('datasource', models.CharField(max_length=256, verbose_name='Data Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('P', 'Processing'), ('S', 'Processed - Success'), ('E', 'Processed - Error')], default='W', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
